name: nutrition_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.11
  flutter_flip_card: ^0.0.6
  intl: ^0.17.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  mime: ^1.0.0
  http_parser: ^4.0.0
  fl_chart: ^0.69.2
  flutter_charts: ^0.5.2
  chart_components: ^1.0.1
  google_fonts: ^6.2.1
  
  # Enhanced functionality
  animations: ^2.0.11
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/splash/logo.png
    - assets/splash/upper-rec.png
    - assets/splash/lower-rec.png

    - assets/welcome/left-rec.png
    - assets/welcome/right-rec.png

    - assets/icons/glogin.png
    - assets/icons/flogin.png
    - assets/icons/xlogin.png

    - assets/auths/upper-rec.png
    - assets/auths/lower-rec.png

    - assets/features/feature1.png
    - assets/features/feature2.png
    - assets/features/feature3.png
    - assets/features/feature4.png
